# Generated by Django 5.2.7 on 2025-10-23 00:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('READY', 'Ready'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current order status (RF-01)', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', help_text='Order priority for kitchen display (RF-01)', max_length=10)),
                ('order_type', models.CharField(choices=[('DINE_IN', 'Dine In'), ('TAKEOUT', 'Takeout'), ('DELIVERY', 'Delivery')], default='DINE_IN', help_text='Type of order', max_length=10)),
                ('table_number', models.CharField(blank=True, help_text='Table number for dine-in orders', max_length=10, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total order amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('estimated_time', models.PositiveIntegerField(default=0, help_text='Estimated preparation time in minutes (RF-04)')),
                ('actual_time', models.PositiveIntegerField(blank=True, help_text='Actual preparation time in minutes (for analytics - RF-06)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Special instructions or notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Order creation timestamp (traceability)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp (RF-04)')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Order completion timestamp (RF-06)', null=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity ordered', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit at time of order', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated subtotal (quantity × unit_price)', max_digits=10)),
                ('special_instructions', models.TextField(blank=True, help_text='Special instructions for this item')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'db_table': 'order_items',
            },
        ),
    ]
