# Generated by Django 5.2.7 on 2025-10-23 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='user',
            field=models.ForeignKey(help_text='User who performed transaction (RNF-04)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['ingredient', 'created_at'], name='inventory_t_ingredi_5fff15_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['transaction_type'], name='inventory_t_transac_a372b6_idx'),
        ),
    ]
